# Generated by Django 4.2.6 on 2024-01-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nick', '0006_title_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='poster_path',
            field=models.URLField(blank=True),
        ),
    ]
