# Generated by Django 4.2.6 on 2024-01-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nick', '0010_alter_title_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
