# Generated by Django 4.2.6 on 2024-01-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nick', '0011_alter_title_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='character',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='title',
            name='credit_type',
            field=models.CharField(blank=True, choices=[('CST', 'Cast'), ('CRW', 'Crew')], max_length=3),
        ),
    ]
