# Generated by Django 4.2.6 on 2024-01-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nick', '0012_title_character_alter_title_credit_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='credit_type',
        ),
    ]
