# Generated by Django 4.2.6 on 2024-01-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nick', '0013_remove_title_credit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='budget',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='revenue',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='runtime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='status',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='title',
            name='tagline',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
