# Generated by Django 4.2.6 on 2024-01-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nick', '0014_title_budget_title_revenue_title_runtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='title',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='keywords', to='nick.keyword'),
        ),
    ]
