# Generated by Django 4.2.6 on 2024-01-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nick', '0016_companies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Companies',
            new_name='Company',
        ),
        migrations.AddField(
            model_name='title',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='companies', to='nick.company'),
        ),
    ]
