# Generated by Django 4.2.6 on 2024-01-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nick', '0017_rename_companies_company_title_companies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='title',
            name='director',
            field=models.ManyToManyField(blank=True, related_name='directed', to='nick.director'),
        ),
    ]
