# Generated by Django 4.2.6 on 2024-01-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nick', '0018_director_title_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='certification',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
