# Generated by Django 5.0.1 on 2024-01-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nick', '0019_title_certification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.AddField(
            model_name='title',
            name='vote_average',
            field=models.FloatField(null=True),
        ),
    ]
