# Generated by Django 4.2.6 on 2024-01-16 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nick', '0020_alter_company_options_title_vote_average'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nick.genre')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nick.title')),
            ],
        ),
    ]
