# Generated by Django 4.2.6 on 2024-01-16 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nick', '0021_genretitle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenreTitle',
        ),
    ]
