# Generated by Django 4.2.6 on 2024-01-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nick', '0022_delete_genretitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='role_type',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=32, verbose_name='genre'),
        ),
    ]
