# Generated by Django 4.2.6 on 2024-01-09 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nick', '0003_genre_movie_overview_movie_release_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Title',
        ),
    ]
