# Generated by Django 4.2.6 on 2024-01-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nick', '0004_rename_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='character',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='title',
            name='title',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
