# Generated by Django 4.2.6 on 2024-01-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nick', '0007_title_poster_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='credit_type',
            field=models.CharField(blank=True, choices=[('ACT', 'Actor'), ('CRW', 'Crew')], max_length=3),
        ),
    ]
