# Generated by Django 4.2.6 on 2024-01-09 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nick', '0008_title_credit_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='character',
            new_name='role',
        ),
    ]
